Repository prgrms-fe-devcourse/FEDC3_Bigtoria_Off, pull requests merged in 2023-01, with the labels that each got.

#5 chore: prettier 수정
  .prettierrc.json
Labels: chore, frontend

#10 chore: mui 패키지 설치
  package-lock.json
  package.json
Labels: chore, frontend

#12 axios 설치
  package-lock.json
  package.json
Labels: chore, frontend

#17 기본 Layout 구성
  package-lock.json
  package.json
  src/App.tsx
  src/components/shared/.empty
  src/components/shared/Header.tsx
  src/constants/.empty
  src/constants/routes.ts
Labels: feature, frontend

#16 NotFound Page
  package-lock.json
  src/pages/.empty
  src/pages/404.tsx
Labels: feature, frontend

#21 story card component 구현
  .prettierrc.json
  package-lock.json
  src/components/StoryPage/.empty
  src/components/StoryPage/StoryItem/StoryCard.tsx
  src/hooks/useLazyLoadImage.ts
Labels: feature, frontend

#23 사용자 검색 로직 기능
  package-lock.json
  src/components/Home/SearchForm/SearchForm.tsx
  src/components/Home/SearchForm/dummy.d.ts
  src/components/Home/SearchForm/dummy.js
Labels: feature, frontend

#28 StoryBook 페이지 개발
  .env.example
  .gitignore
  src/App.tsx
  src/assets/.empty
  src/assets/images/defaultImage.png
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryCard.tsx
  src/constants/errorMessages.ts
  src/constants/routes.ts
  src/hooks/useFetchStories.ts
  src/hooks/useLazyLoadImage.ts
  src/interfaces/story.ts
  src/pages/StoryBook.tsx
Labels: feature, frontend

#30 eslint 규칙 강화 및 템플릿 추가
  .eslintrc.json
  .github/ISSUE_TEMPLATE/custom-template-for-quiz.md
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/App.tsx
  src/components/Home/SearchForm/SearchForm.tsx
  src/components/Story/DatePicker.tsx
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryCard.tsx
  src/components/signup/SignUpButton.tsx
  src/components/signup/SignUpForm.tsx
  src/hooks/useFetchStories.ts
  src/hooks/useLazyLoadImage.ts
  src/main.tsx
  src/pages/StoryBook.tsx
  vite.config.ts
Labels: chore, documentation, frontend, refactor

#31 feat: develop 1차 병합 + 템플릿 추가 + 애러 해결
  .env.example
  .eslintrc.json
  .github/ISSUE_TEMPLATE/custom-template-for-quiz.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/apis/.empty
  src/assets/.empty
  src/assets/images/defaultImage.png
  src/components/Home/SearchForm/SearchForm.tsx
  src/components/Home/SearchForm/dummy.d.ts
  src/components/Home/SearchForm/dummy.js
  src/components/Story/DatePicker.tsx
  src/components/Story/TextInput.tsx
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryCard.tsx
  src/components/shared/Header.tsx
  src/components/signup/SignUpButton.tsx
  src/components/signup/SignUpForm.tsx
  src/components/signup/SignUpInput.tsx
  src/constants/errorMessages.ts
  src/constants/routes.ts
  src/hooks/useFetchStories.ts
  src/hooks/useLazyLoadImage.ts
  src/interfaces/story.ts
  src/main.tsx
  src/pages/404.tsx
  src/pages/SignUp.tsx
  src/pages/StoryBook.tsx
  src/styles/GlobalStyle.tsx
  src/utils/.empty
  vite.config.ts
Labels: bug, chore, documentation, feature, fix, frontend, refactor

#33 스토리 작성 페이지
  src/components/Story/TextInput.tsx
  src/components/StoryEdit/DatePicker.tsx
  src/components/StoryEdit/ImageInput.tsx
  src/components/StoryEdit/StoryEditForm.tsx
  src/components/StoryEdit/SubmitButton.tsx
  src/components/StoryEdit/TextInput.tsx
  src/hooks/useStoryForm.ts
  src/interfaces/story.ts
  src/pages/StoryEdit.tsx
Labels: feature, frontend

#38 회원가입 컴포넌트 폴더명 변경
  src/components/SignUp/SignUpButton.tsx
  src/components/SignUp/SignUpForm.tsx
  src/components/SignUp/SignUpInput.tsx
  src/components/SignUp/SignUpSelector.tsx
  src/pages/SignUp.tsx
Labels: chore, frontend

#41 Feature/Home - 사용자 목록 컴포넌트
  src/App.tsx
  src/apis/search.ts
  src/components/Home/SearchForm/SearchForm.tsx
  src/components/Home/UserList/UserList.tsx
  src/components/Home/dummy.d.ts
  src/components/Home/dummy.js
  src/interfaces/user.ts
  src/pages/Home.tsx
Labels: feature, frontend

#40 햄버거 메뉴 기능 개발
  index.html
  public/icons/close.svg
  public/icons/hamburger_menu.svg
  public/icons/user_profile.svg
  src/components/shared/Header.tsx
Labels: feature, frontend

#36 axiosInstance 생성
  package-lock.json
  src/apis/.empty
  src/apis/instance.ts
  src/apis/story.ts
  src/constants/httpMethods.ts
  src/hooks/useFetchStories.ts
  src/utils/.empty
  src/utils/storage.ts
Labels: feature, frontend

#48 husky + lint staged
  .husky/pre-commit
  package-lock.json
  package.json
Labels: chore, feature, frontend

#49 API URLs 작성
  src/constants/apiUrls.ts
Labels: feature, frontend, refactor

#50 회원가입 기능구현
  src/components/SignUp/SignUpForm.tsx
  src/hooks/useForm.ts
Labels: feature, frontend

#52 Design/ 사용자 목록 컴포넌트 스타일링
  package-lock.json
  package.json
  src/components/Home/NoResultBox.tsx
  src/components/Home/SearchForm.tsx
  src/components/Home/SearchForm/SearchForm.tsx
  src/components/Home/Title.tsx
  src/components/Home/UserList.tsx
  src/components/Home/UserList/UserList.tsx
  src/components/Home/UserProfile.tsx
  src/components/Home/dummy.d.ts
  src/components/Home/dummy.js
  src/components/Home/title.css
  src/pages/Home.tsx
Labels: frontend, style

#53 스토리 페이지 레이아웃
  package-lock.json
  src/components/Story/CommentForm.tsx
  src/components/Story/CommentItem.tsx
  src/components/Story/CommentList.tsx
  src/components/Story/LikeButton.tsx
  src/interfaces/comment.ts
  src/interfaces/like.ts
  src/pages/Story.tsx
Labels: feature, frontend

#55 회원가입 페이지 리팩터링
  src/apis/signup.ts
  src/components/SignUp/SignUpForm.tsx
  src/hooks/useForm.ts
  src/hooks/useSignUpForm.ts
  src/interfaces/signUp.ts
  src/pages/SignUp.tsx
  src/utils/signUpIsValid.ts
  src/utils/signUpValidate.ts
Labels: frontend, refactor

#56 사용자 목록 api 수정
  src/apis/search.ts
  src/components/Home/FontText.tsx
  src/components/Home/NoResultBox.tsx
  src/components/Home/SearchForm.tsx
  src/components/Home/UserList.tsx
  src/components/Home/UserProfile.tsx
  src/components/Home/fontText.css
  src/components/shared/Header.tsx
  src/hooks/useFetchUserList.ts
  src/hooks/useSearchForm.ts
  src/interfaces/user.ts
  src/pages/Home.tsx
Labels: frontend, refactor, style

#63 style: prettier bracketSameLine: true 옵션 추가
  .eslintrc.json
  .prettierrc.json
Labels: frontend, style

#64 햄버거에 cursor: pointer 추가
  src/components/shared/Header.tsx
Labels: frontend, style

#65 realTitle에서 storyTitle로 변수명 개선
  src/components/StoryBook/StoriesByYear.tsx
  src/interfaces/story.ts
Labels: feature, refactor

#66 알림페이지 레이아웃
  src/App.tsx
  src/components/Alarm/NotificationList.tsx
  src/components/Alarm/NotificationMsg.tsx
  src/components/Alarm/TabContainer.tsx
  src/components/Alarm/TabItem.tsx
  src/constants/routes.ts
  src/pages/Home.tsx
  src/pages/Notification.tsx
Labels: frontend, style

#71 로그아웃 api 구현
  src/App.tsx
  src/apis/auth.ts
  src/apis/instance.ts
  src/constants/http.ts
  src/utils/storage.ts
Labels: feature, frontend

#67 스토리 추가 및 조회 페이지 API 연동
  src/App.tsx
  src/apis/story.ts
  src/components/Story/CommentForm.tsx
  src/components/Story/CommentItem.tsx
  src/components/Story/CommentList.tsx
  src/components/Story/StoryComment.tsx
  src/components/Story/StoryInfo.tsx
  src/components/StoryEdit/StoryEditForm.tsx
  src/components/StoryEdit/SubmitButton.tsx
  src/constants/errorMessages.ts
  src/constants/routes.ts
  src/hooks/useComment.ts
  src/hooks/useFetchStory.ts
  src/hooks/useStory.ts
  src/hooks/useStoryForm.ts
  src/interfaces/comment.ts
  src/interfaces/story.ts
  src/pages/Story.tsx
  src/pages/StoryEdit.tsx
Labels: feature, frontend

#73 스토리 수정 기능
  src/apis/auth.ts
  src/apis/story.ts
  src/components/Story/CommentForm.tsx
  src/components/Story/CommentList.tsx
  src/components/Story/StoryComment.tsx
  src/components/Story/StoryInfo.tsx
  src/components/StoryEdit/StoryEditForm.tsx
  src/components/StoryEdit/TextInput.tsx
  src/constants/errorMessages.ts
  src/constants/routes.ts
  src/hooks/useComment.ts
  src/hooks/useFetchStory.ts
  src/hooks/useFetchUser.ts
  src/hooks/useStory.ts
  src/interfaces/story.ts
  src/pages/Story.tsx
  src/pages/StoryEdit.tsx
  src/utils/validations.ts
Labels: feature, fix, frontend

#76 스토리 추가 버튼 구현
  src/apis/story.ts
  src/components/StoryBook/StoryAddButton.tsx
  src/components/StoryBook/StoryCard.tsx
  src/pages/StoryBook.tsx
Labels: feature, frontend

#78 SearchForm 공백 에러 처리 및 home header 로고 수정
  src/components/Home/SearchForm.tsx
  src/components/shared/Header.tsx
  src/hooks/useSearchForm.ts
  src/utils/validationSearchForm.ts
Labels: frontend, refactor, style

#79 스토리 좋아요 기능 구현
  src/apis/story.ts
  src/components/Story/LikeButton.tsx
  src/components/Story/StoryInfo.tsx
  src/constants/errorMessages.ts
  src/hooks/useFetchUser.ts
  src/hooks/useLike.ts
  src/hooks/useStory.ts
Labels: feature, frontend

#83 스토리 카드 위에 month 추가
  src/App.tsx
  src/components/StoryBook/Loading.tsx
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryAddButton.tsx
  src/components/StoryBook/StoryCard.tsx
  src/components/shared/Header.tsx
  src/constants/routes.ts
  src/hooks/useCheckAuthToken.ts
  src/hooks/useFetchStories.ts
  src/interfaces/story.ts
  src/pages/StoryBook.tsx
Labels: feature, frontend, refactor, style

#88 채팅 개발 및 여러가지 교통 정리
  package.json
  src/components/Message/MessageBubble.tsx
  src/components/Message/MessageConversation.tsx
  src/components/Message/MessageInputForm.tsx
  src/components/shared/Header.tsx
  src/interfaces/message.ts
  src/pages/Chat.tsx
  src/styles/GlobalStyle.tsx
Labels: bug, chore, feature, fix, frontend, refactor, style

#89 follow page
  package-lock.json
  src/App.tsx
  src/apis/follow.ts
  src/apis/getFollowingUser.ts
  src/apis/userInfo.ts
  src/assets/.empty
  src/components/Follow/FollowingList.tsx
  src/components/StoryEdit/SubmitButton.tsx
  src/components/shared/Header.tsx
  src/constants/routes.ts
  src/hooks/useGetFollow.ts
  src/interfaces/user.ts
  src/pages/Following.tsx
Labels: bug, feature, frontend, style

#93 README 파일 1차 작성
  README.md
Labels: documentation, frontend

#95 햄버거 메뉴(사이드바)에 라우팅 설정.
  src/components/SignIn/SignInForm.tsx
  src/components/shared/Header.tsx
  src/components/shared/SignInButton.tsx
  src/constants/routes.ts
Labels: feature, frontend, style

#94 Feature, Refactor/ 사용자 목록 무한 스크롤, 사용자 스토리 url추가
  README.md
  package.json
  src/App.tsx
  src/apis/search.ts
  src/components/Alarm/TabContainer.tsx
  src/components/Home/UserList.tsx
  src/constants/apiParams.ts
  src/hooks/useFetchUserList.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useIntersectionObserver.ts
  src/pages/Home.tsx
  src/pages/Notification.tsx
Labels: feature, frontend, refactor

#98 userId에 따라 follow 페이지로 라우팅되도록 구현
  src/App.tsx
  src/apis/auth.ts
  src/components/SignIn/SignInLinks.tsx
  src/components/StoryBook/StoryAddButton.tsx
  src/components/StoryEdit/SubmitButton.tsx
  src/components/shared/Header.tsx
  src/constants/auth.ts
  src/constants/routes.ts
  src/hooks/useFetchStories.ts
  src/hooks/useGetFollow.ts
Labels: feature, frontend

#100 스토리 조회 페이지 레이아웃 수정, 작성 에러 해결
  src/App.tsx
  src/apis/story.ts
  src/components/Story/CommentForm.tsx
  src/components/Story/CommentList.tsx
  src/components/Story/StoryComment.tsx
  src/components/Story/StoryInfo.tsx
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryEdit/StoryEditForm.tsx
  src/components/shared/ScrollToTop.tsx
  src/hooks/useComment.ts
  src/hooks/useFetchStories.ts
  src/hooks/useFetchUser.ts
  src/hooks/useLike.ts
  src/hooks/useStory.ts
  src/pages/StoryEdit.tsx
Labels: fix, frontend, style

#103 SignInLinks 버튼 텍스트 변경
  src/components/SignIn/SignInLinks.tsx
  src/hooks/useFetchStories.ts
  src/pages/SignIn.tsx
Labels: feature, frontend

#104 알림 헤더 아이콘 추가
  src/components/Alarm/NotificationButton.tsx
  src/components/Home/FontText.tsx
  src/components/shared/Header.tsx
  src/pages/Home.tsx
Labels: feature, frontend

#107 팔로우페이지 레이아웃 변경
  src/pages/Following.tsx
Labels: frontend, style

#108 댓글, 좋아요, 팔로우 알림 생성
  src/apis/notification.ts
  src/apis/story.ts
  src/hooks/useComment.ts
  src/hooks/useGetFollow.ts
  src/hooks/useLike.ts
Labels: feature, frontend

#110 useFetchStories sort issue 해결
  src/hooks/useFetchStories.ts
Labels: fix, frontend

#112 사용자 알림 목록 조회
  src/apis/notification.ts
  src/components/Alarm/NotificationButton.tsx
  src/components/Alarm/NotificationList.tsx
  src/components/Alarm/NotificationMsg.tsx
  src/components/Home/UserList.tsx
  src/components/Story/StoryInfo.tsx
  src/constants/routes.ts
  src/hooks/useComment.ts
  src/interfaces/notification.ts
  src/pages/Home.tsx
  src/pages/Notification.tsx
  src/utils/calcCreatedToCurrentTime.ts
Labels: feature, frontend, style

#119 StoryCard, 스크롤바, Header 디자인
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryCard.tsx
  src/components/shared/Header.tsx
  src/constants/color.ts
  src/constants/colors.ts
Labels: feature, design

#117 팔로우 페이지 추가기능
  src/apis/follow.ts
  src/components/Follow/FollowingButton.tsx
  src/components/Follow/FollowingList.tsx
  src/hooks/useGetFollow.ts
  src/pages/Following.tsx
Labels: feature, fix, frontend, style

#120 스토리 사진 업로드 방식 추가, 스토리 페이지 스타일 수정
  src/components/Story/LikeButton.tsx
  src/components/Story/StoryInfo.tsx
  src/components/StoryEdit/DatePicker.tsx
  src/components/StoryEdit/ImageUpload.tsx
  src/components/StoryEdit/StoryEditForm.tsx
  src/hooks/useStory.ts
  src/pages/Story.tsx
  src/pages/StoryEdit.tsx
Labels: feature, fix, frontend, design

#121 본인이 작성한 스토리의 댓글과 좋아요 알림 미생성
  src/components/Story/StoryComment.tsx
  src/hooks/useComment.ts
  src/hooks/useLike.ts
  src/pages/Story.tsx
Labels: fix, frontend

#122 채팅 UI 및 기본 틀
  src/components/Message/MessageBubble.tsx
  src/components/Message/MessageConversation.tsx
  src/components/Message/MessageInputForm.tsx
  src/interfaces/message.ts
  src/pages/Chat.tsx
Labels: feature, frontend, refactor, style

#123 알림 확인
  src/apis/notification.ts
  src/components/Alarm/NotificationButton.tsx
  src/components/Alarm/NotificationList.tsx
  src/components/Alarm/NotificationMsg.tsx
  src/pages/Notification.tsx
Labels: feature, frontend

#125 사용자 검색 리팩토링 및 검색 키워드 무한스크롤 적용
  src/apis/search.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useSearchForm.ts
  src/pages/Home.tsx
  src/utils/validationSearchForm.ts
Labels: feature, fix, frontend, refactor

#126 SignUpForm 컴포넌트 안의 요소들을 mui로 대체
  src/apis/signup.ts
  src/components/SignUp/SignUpInput.tsx
  src/components/SignUp/SignUpSelector.tsx
  src/components/shared/Header.tsx
  src/hooks/useSignUpForm.ts
  src/interfaces/signUp.ts
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/utils/signUpIsValid.ts
  src/utils/signUpValidate.ts
Labels: frontend, design

#128 StoryBook 페이지에서 rootMargin, threshold를 변경해 보이지 않더라도 어느정도의 사진은 불러오기
  src/components/StoryBook/Empty.tsx
  src/hooks/useLazyLoadImage.ts
  src/pages/StoryBook.tsx
Labels: feature, frontend

#129 팔로우 페이지 리팩터링
  src/components/Follow/FollowingButton.tsx
  src/components/Follow/FollowingList.tsx
  src/hooks/useGetFollow.ts
  src/interfaces/followList.ts
  src/pages/Following.tsx
  src/utils/getChangedIndex.ts
Labels: frontend, refactor, style

#133 홈 화면, 스토리북에서 스크롤에 의해 발생하는 레이아웃 쉬프트 제거
  src/components/shared/Header.tsx
  src/styles/GlobalStyle.tsx
Labels: feature, design

#134 회원가입 페이지 수정
  src/components/SignUp/SignUpInput.tsx
  src/hooks/useSignUpForm.ts
  src/pages/SignUp.tsx
  src/utils/signUpValidate.ts
Labels: frontend, refactor, design

#131 좋아요, 댓글 알림 사용자 Id재설정 및 알림 목록 setInterval 추가
  src/components/Story/LikeButton.tsx
  src/components/Story/StoryInfo.tsx
  src/hooks/useComment.ts
  src/hooks/useLike.ts
  src/pages/Notification.tsx
  src/utils/calcCreatedToCurrentTime.ts
Labels: feature, fix, frontend

#139 프로필 설정 페이지
  src/App.tsx
  src/apis/userInfo.ts
  src/components/Profile/ImageForm.tsx
  src/components/Profile/PasswordForm.tsx
  src/components/Profile/ProfileModal.tsx
  src/components/Profile/TextForm.tsx
  src/components/Story/CommentItem.tsx
  src/components/StoryEdit/ImageUpload.tsx
  src/components/StoryEdit/StoryEditForm.tsx
  src/components/StoryEdit/TextInput.tsx
  src/components/shared/Header.tsx
  src/constants/errorMessages.ts
  src/constants/routes.ts
  src/pages/Profile.tsx
Labels: feature, frontend

#137 알림 삭제 및 팔로우 연결, 헤더 클릭 아이콘 간단 기능 추가
  src/components/Alarm/NotificationButton.tsx
  src/components/Alarm/NotificationList.tsx
  src/components/Alarm/NotificationMsg.tsx
  src/components/StoryBook/FollowButton.tsx
  src/components/StoryBook/StoryAddButton.tsx
  src/components/shared/Header.tsx
  src/hooks/useGetFollow.ts
  src/utils/calcCreatedToCurrentTime.ts
Labels: feature, frontend, refactor

#141 사용자 검색 유효성 검사 추가 작성
  src/hooks/useDebounce.ts
  src/hooks/useSearchForm.ts
  src/hooks/useTimeoutFn.ts
  src/pages/Home.tsx
  src/utils/validationSearchForm.ts
Labels: frontend, refactor

#144 App 전반적으로 디자인 진행
  package-lock.json
  package.json
  src/components/Alarm/NotificationButton.tsx
  src/components/Alarm/NotificationMsg.tsx
  src/components/Alarm/TabItem.tsx
  src/components/Follow/FollowingButton.tsx
  src/components/Home/FontText.tsx
  src/components/Home/SearchForm.tsx
  src/components/Home/UserProfile.tsx
  src/components/SignIn/SignInForm.tsx
  src/components/SignIn/SignInLinks.tsx
  src/components/SignUp/SignUpButton.tsx
  src/components/SignUp/SignUpInput.tsx
  src/components/Story/CommentForm.tsx
  src/components/Story/CommentList.tsx
  src/components/Story/LikeButton.tsx
  src/components/Story/StoryInfo.tsx
  src/components/StoryBook/FollowButton.tsx
  src/components/StoryBook/Loading.tsx
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryAddButton.tsx
  src/components/StoryEdit/DatePicker.tsx
  src/components/StoryEdit/ImageUpload.tsx
  src/components/StoryEdit/SubmitButton.tsx
  src/components/StoryEdit/TextInput.tsx
  src/components/shared/Header.tsx
  src/components/shared/SignInButton.tsx
  src/constants/colors.ts
  src/main.tsx
  src/pages/Following.tsx
  src/pages/Home.tsx
  src/pages/Notification.tsx
  src/pages/StoryBook.tsx
  src/styles/FontStyle.tsx
  src/styles/GlobalStyle.tsx
Labels: frontend, design

#147 머지 에러 해결
  package-lock.json
  package.json
  src/components/Profile/ImageForm.tsx
  src/components/Profile/PasswordForm.tsx
  src/components/Profile/ProfileModal.tsx
  src/components/Profile/TextForm.tsx
  src/components/shared/Header.tsx
  src/hooks/useLike.ts
  src/hooks/useStory.ts
  src/pages/Profile.tsx
Labels: fix, frontend

#146 스토리북 디자인
  src/components/StoryBook/StoriesByYear.tsx
Labels: frontend, design

#148 월이 계속 찍히는 현상 해결
  src/components/StoryBook/StoriesByYear.tsx
Labels: fix, frontend, design

#149 @esbuild/darwin-x64 패키지 삭제
  package-lock.json
  package.json
Labels: fix, frontend

#151 Design/bigtoria
  src/components/Home/SearchForm.tsx
  src/components/Home/UserProfile.tsx
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryCard.tsx
  src/components/shared/Header.tsx
  src/pages/Home.tsx
Labels: frontend, design

#152 생년월일 기준 첫 스토리 생성
  src/constants/apiParams.ts
  src/hooks/useSignUpForm.ts
  src/hooks/useStory.ts
Labels: feature, frontend

#153 홈화면 리팩터링
  src/components/Home/SearchForm.tsx
  src/components/Home/UserList.tsx
  src/hooks/useSearchForm.ts
  src/pages/Home.tsx
Labels: fix, frontend, refactor

#154 팔로우 리팩토링
  src/components/Follow/FollowingButton.tsx
  src/components/Follow/FollowingList.tsx
  src/components/StoryBook/FollowButton.tsx
  src/pages/Following.tsx
Labels: frontend, refactor, style

#155 헤더, 햄버거 안정화
  src/components/shared/Header.tsx
Labels: bug, frontend, refactor, style, design

#156 화면 전체 흔들림 해결 및 스토리 추가 페이지 화면 깜빡임 해결
  src/components/shared/Header.tsx
  src/pages/StoryEdit.tsx
  src/styles/GlobalStyle.tsx
Labels: bug, fix, frontend, refactor, style, design

#157 follow 안정성 개선
  src/apis/notification.ts
  src/hooks/useFetchStories.ts
  src/pages/StoryBook.tsx
Labels: bug, fix, frontend, refactor

#159 StoriesByYear에서 key prop 중복되는 현상 관련 임시로 원상 복구
  src/pages/StoryBook.tsx
Labels: fix, frontend

#160 프로필 설정 페이지 디자인 적용
  src/components/Profile/ImageForm.tsx
  src/components/Profile/PasswordForm.tsx
  src/components/Profile/TextForm.tsx
  src/pages/Profile.tsx
Labels: frontend, design

#161 home fontText 삭제 및 Typography 도입
  src/components/Home/FontText.tsx
  src/components/Home/SearchForm.tsx
  src/components/Home/fontText.css
  src/components/Notification/NotificationButton.tsx
  src/components/Notification/NotificationList.tsx
  src/components/Notification/NotificationMsg.tsx
  src/components/Notification/TabContainer.tsx
  src/components/Notification/TabItem.tsx
  src/components/shared/Header.tsx
  src/pages/Home.tsx
  src/pages/Notification.tsx
Labels: frontend, refactor

#162 파비콘 및 메타태그 추가
  README.md
  index.html
  public/favicon.png
  public/share.png
  public/vite.svg
Labels: documentation, design

#164 fix: infinite scroll bound값 올바른 값 설정
  src/hooks/useInfiniteScroll.ts
Labels: fix, frontend

#165 notification message 디자인 작업
  src/components/Home/UserProfile.tsx
  src/components/Notification/NotificationMsg.tsx
  src/pages/Notification.tsx
  src/pages/StoryBook.tsx
Labels: frontend, design

#167 다크모드 구현
  src/App.tsx
  src/components/Home/SearchForm.tsx
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryEdit/DatePicker.tsx
  src/components/StoryEdit/ImageUpload.tsx
  src/components/shared/DarkModeSwitch.tsx
  src/components/shared/Header.tsx
  src/constants/auth.ts
  src/constants/colors.ts
  src/contexts/DisplayModeContext.tsx
  src/interfaces/displayMode.ts
  src/main.tsx
  src/styles/GlobalStyle.tsx
  src/utils/helpers.ts
Labels: feature, frontend, design

#169 사용자 검색 이미지 우선 보여주기
  src/apis/search.ts
  src/hooks/useInfiniteScroll.ts
  src/utils/setUserListImageFirst.ts
Labels: feature, frontend

#172 Feat/empty followpage
  src/components/Follow/FollowEmpty.tsx
  src/components/Follow/FollowingButton.tsx
  src/pages/Follower.tsx
  src/pages/Following.tsx
Labels: feature, fix, frontend

#173 Date picker 버튼 텍스트 색 변경
  src/components/Home/UserProfile.tsx
  src/components/Story/CommentList.tsx
  src/components/Story/StoryInfo.tsx
  src/components/shared/Header.tsx
  src/contexts/DisplayModeContext.tsx
Labels: frontend, design

#175 github action
  .github/workflows/production.yaml
  .gitignore
Labels: chore, frontend

#176 알림 SWR 적용
  package-lock.json
  package.json
  src/apis/notification.ts
  src/components/Notification/NotificationButton.tsx
  src/components/Notification/TabContainer.tsx
  src/contexts/NotificationContext.tsx
  src/main.tsx
  src/pages/Notification.tsx
Labels: feature, frontend, refactor

#178 메이플스토리체 안 먹히는 현상 해결
  package-lock.json
  src/contexts/DisplayModeContext.tsx
  src/main.tsx
Labels: fix, frontend, design

#179 리다이렉팅 설정
  vercel.json
Labels: chore, frontend

#177 GitHub action + Licence
  .github/workflows/preview.yaml
  Licence
Labels: chore, feature

#181 vercel json router 해결
  .github/workflows/production.yaml
  vercel.json
Labels: bug, fix, frontend

#183 채팅 팔로우 연동 및 내용 전달
  .eslintrc.json
  .github/workflows/preview.yaml
  .github/workflows/production.yaml
  src/App.tsx
  src/components/Follow/FollowModal.tsx
  src/components/Message/MessageInputForm.tsx
  src/components/SignUp/SignUpButton.tsx
  src/pages/Chat.tsx
Labels: feature, frontend, refactor

#184 채팅 개발
  src/components/Message/MessageBubble.tsx
  src/components/Message/MessageInputForm.tsx
  src/interfaces/message.ts
  src/pages/Chat.tsx
Labels: feature, frontend, refactor, style

#185 유효성 검사 최종
  src/components/SignUp/SignUpInput.tsx
  src/components/StoryEdit/DatePicker.tsx
  src/hooks/useSignUpForm.ts
  src/pages/SignUp.tsx
  src/utils/signUpValidate.ts
Labels: frontend, refactor

#189 Vercel 리다이렉팅 설정
  .github/workflows/production.yaml
Labels: chore, frontend

#190 Vercel 리다이렉팅 재설정
  .github/workflows/production.yaml
Labels: chore, feature

#191 리다이렉팅 원복
  .github/workflows/production.yaml
Labels: chore, frontend

#192 리다이렉팅 원복
  .github/workflows/production.yaml
Labels: chore, frontend

#187 알림 목록 디자인 누락 및 다크모드 디자인 수정
  src/components/Home/SearchForm.tsx
  src/components/Home/UserProfile.tsx
  src/components/Message/MessageInputForm.tsx
  src/components/Notification/NotificationMsg.tsx
  src/components/Notification/TabContainer.tsx
  src/pages/Home.tsx
  src/pages/Notification.tsx
Labels: frontend, design

#193 vercel 리다이렉팅
  .github/workflows/production.yaml
Labels: chore, frontend

#186 storybook 로직 개선
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryCard.tsx
  src/pages/Story.tsx
Labels: frontend, refactor

#188 story layout 개선
  src/components/Story/StoryInfo.tsx
Labels: refactor, style

#194 팔로우 페이지 리뉴얼
  src/App.tsx
  src/components/Follow/FollowHeader.tsx
  src/pages/Follower.tsx
  src/pages/Following.tsx
  src/pages/follow.tsx
Labels: feature, frontend, refactor, style, design

#195 글로벌 리팩토링
  README.md
  public/MaplestoryOTFLight.woff2
  src/components/shared/Header.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/styles/FontStyle.tsx
  src/styles/GlobalStyle.tsx
Labels: frontend, refactor

#196 프로필 이미지 크기 및 모달 창 디자인 수정
  src/components/Profile/ImageForm.tsx
  src/components/Profile/PasswordForm.tsx
  src/components/Profile/ProfileModal.tsx
  src/components/Profile/TextForm.tsx
  src/components/StoryEdit/ImageUpload.tsx
  src/pages/Profile.tsx
Labels: frontend, design

#197 header 리팩터링
  src/components/shared/Header.tsx
  src/hooks/useIsOverByScroll.ts
Labels: frontend, refactor

#200 회원가입 닉네임 중복
  src/apis/userList.ts
  src/components/SignUp/SignUpInput.tsx
  src/hooks/useSignUpForm.ts
  src/pages/SignUp.tsx
  src/utils/signUpValidate.ts
Labels: feature, fix, frontend

#204 알림 메세지 연결
  src/components/Message/MessageInputForm.tsx
  src/components/Notification/NotificationMsg.tsx
  src/components/Notification/TabContainer.tsx
  src/utils/validationSearchForm.ts
Labels: feature, frontend

#206 스토리 쓰기 후 에러 뜨는 버그 해결
  src/hooks/useStory.ts
Labels: fix, frontend

#207 version 1.0.0
  package-lock.json
  package.json
  src/components/Message/MessageInputForm.tsx
  src/pages/Chat.tsx
Labels: chore

#208 스토리 수정 페이지 진입 후 스토리 추가 버튼 눌렀을 때 리렌더링 처리
  src/components/StoryEdit/StoryEditForm.tsx
  src/hooks/useSignUpForm.ts
  src/hooks/useStory.ts
  src/interfaces/story.ts
  src/pages/StoryEdit.tsx
  src/utils/helpers.ts
Labels: feature, fix

#209 notification message 연결 해제
  README.md
  src/components/Notification/NotificationList.tsx
  src/components/Notification/NotificationMsg.tsx
  src/components/Notification/TabContainer.tsx
  src/contexts/NotificationContext.tsx
Labels: frontend, refactor

#211 중복 닉네임 버그 수정
  src/hooks/useSignUpForm.ts
Labels: fix, frontend

#213 헤더 감추기
  src/components/shared/Header.tsx
Labels: bug, fix, frontend

#214 헤더 다시 돌리기
  src/components/shared/Header.tsx
Labels: bug, fix, frontend

#216 Story 이미지 크기 조정
  src/components/Story/StoryInfo.tsx
Labels: frontend, design

#218 StoryBook 페이지에서 타이틀 클릭 시 해당 스토리북의 정보를 모달로 출력
  src/components/Follow/FollowModal.tsx
  src/components/StoryBook/StoryBookTitle.tsx
  src/hooks/useFetchStories.ts
  src/pages/StoryBook.tsx
Labels: feature, frontend

#219 스토리 및 댓글 폼 레이아웃 수정
  src/components/Story/CommentForm.tsx
  src/components/Story/StoryInfo.tsx
Labels: frontend, design

#221 스토리 수정 시 날짜 데이터 유지 안 되는 현상 해결
  README.md
  src/components/StoryEdit/DatePicker.tsx
  src/components/StoryEdit/ImageInput.tsx
  src/components/StoryEdit/ImageUpload.tsx
  src/components/StoryEdit/StoryEditForm.tsx
  src/components/StoryEdit/TextInput.tsx
  src/hooks/useStory.ts
Labels: bug, fix, frontend

#222 다크모드에서 팔로잉 버튼 안 보이는 현상 해결
  src/components/StoryBook/FollowButton.tsx
  src/pages/follow.tsx
Labels: fix, frontend, design

#225 닉네임/직업 변경 시 생년월일 데이터 유실되는 현상 해결
  src/apis/userList.ts
  src/components/Profile/PasswordForm.tsx
  src/components/Profile/ProfileModal.tsx
  src/components/Profile/TextForm.tsx
  src/hooks/useSignUpForm.ts
  src/pages/Profile.tsx
Labels: bug, fix, frontend

#224 Google Analytics 연동
  .env.example
  package-lock.json
  package.json
  src/App.tsx
  src/RouteChangeTracker.ts
  src/main.tsx
Labels: feature, frontend

#228 design: 404페이지
  src/assets/images/notFound.png
  src/pages/404.tsx
Labels: frontend, design

#229 404페이지 이미지 크기조정
  src/pages/404.tsx
Labels: frontend, design

#230 web accessibility
  src/components/Profile/ProfileModal.tsx
  src/components/Story/CommentForm.tsx
  src/components/Story/StoryInfo.tsx
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryBookTitle.tsx
  src/components/StoryBook/StoryCard.tsx
  src/components/shared/DarkModeSwitch.tsx
  src/pages/Home.tsx
Labels: frontend, refactor

#233 ProfileModal 타이틀 폰트 사이즈 조정
  src/components/Profile/ProfileModal.tsx
Labels: frontend, design

#232 StoryBook 페이지 버그 해결 및 Image 로딩 시 Spinner 출력
  src/components/StoryBook/StoriesByYear.tsx
  src/components/StoryBook/StoryCard.tsx
Labels: fix, frontend, design

#234 팔로우 페이지 다크모드
  src/components/Follow/FollowingButton.tsx
  src/components/Follow/FollowingList.tsx
  src/pages/follow.tsx
Labels: frontend, refactor, design
